import mongoose from "mongoose";
import dotenv from "dotenv";
import dns from "dns";
import Vehicle from "./models/Vehicle.js";

dotenv.config();

try {
  dns.setServers(["8.8.8.8", "1.1.1.1"]);
} catch (e) {}

const MONGO_URI =
  process.env.MONGO_URI ||
  "mongodb+srv://bhimadev26_db_user:jsL6yYJ1f6QBxHvY@67.osprb3a.mongodb.net/rideinbls?retryWrites=true&w=majority&appName=67";

export const twentyVehicles = [
  // --- 1. PREMIUM SEDANS ---
  {
    name: "Honda City 5th Gen ZX",
    brand: "Honda",
    type: "sedan",
    seats: 5,
    capacity: 5,
    pricePerKM: 14,
    pricePerHour: 180,
    isAvailable: true,
    isBooked: false,
    baseLocation: "Balasore",
    currentLocation: "Balasore City Center",
    licensePlate: "OD-01-AB-1001",
    fuelType: "Petrol",
    transmission: "Automatic",
    year: 2024,
    color: "Platinum White Pearl",
    features: ["Sunroof", "LaneWatch Camera", "Leather Seats", "Fastag", "Air Purifier"],
    description: "Executive premium sedan with supreme legroom and plush leather seating.",
    images: [{ url: "https://images.unsplash.com/photo-1549399542-7e3f8b79c341?auto=format&fit=crop&w=800&q=80", public_id: "v_honda_city", format: "jpg" }],
  },
  {
    name: "Hyundai Verna Turbo DCT",
    brand: "Hyundai",
    type: "sedan",
    seats: 5,
    capacity: 5,
    pricePerKM: 15,
    pricePerHour: 190,
    isAvailable: true,
    isBooked: false,
    baseLocation: "Bhubaneswar",
    currentLocation: "Master Canteen Square",
    licensePlate: "OD-02-CD-2002",
    fuelType: "Petrol",
    transmission: "Automatic",
    year: 2024,
    color: "Abyss Black",
    features: ["ADAS Level 2", "Ventilated Seats", "Bose 8-Speaker Audio", "Wireless Charger"],
    description: "Futuristic fastback sedan with turbocharged performance and ADAS safety.",
    images: [{ url: "https://images.unsplash.com/photo-1552519507-da3b142c6e3d?auto=format&fit=crop&w=800&q=80", public_id: "v_verna_turbo", format: "jpg" }],
  },
  {
    name: "Skoda Slavia 1.5 TSI",
    brand: "Skoda",
    type: "sedan",
    seats: 5,
    capacity: 5,
    pricePerKM: 16,
    pricePerHour: 200,
    isAvailable: true,
    isBooked: false,
    baseLocation: "Cuttack",
    currentLocation: "Badambadi Bus Terminal",
    licensePlate: "OD-05-EF-3003",
    fuelType: "Petrol",
    transmission: "DSG Automatic",
    year: 2023,
    color: "Crystal Blue",
    features: ["521L Boot Space", "Ventilated Front Seats", "Cruise Control", "Sunroof"],
    description: "European build quality offering highway stability and massive luggage capacity.",
    images: [{ url: "https://images.unsplash.com/photo-1541899481282-d53bffe3c35d?auto=format&fit=crop&w=800&q=80", public_id: "v_skoda_slavia", format: "jpg" }],
  },
  {
    name: "Volkswagen Virtus GT Plus",
    brand: "Volkswagen",
    type: "sedan",
    seats: 5,
    capacity: 5,
    pricePerKM: 17,
    pricePerHour: 210,
    isAvailable: true,
    isBooked: false,
    baseLocation: "Bhubaneswar",
    currentLocation: "Patia Infocity Hub",
    licensePlate: "OD-02-GH-4004",
    fuelType: "Petrol",
    transmission: "Automatic",
    year: 2024,
    color: "Wild Cherry Red",
    features: ["GT Badging", "Digital Cockpit", "Paddle Shifters", "5-Star GNCAP Safety"],
    description: "Sporty performance sedan designed for safe and dynamic intercity highway cruising.",
    images: [{ url: "https://images.unsplash.com/photo-1617814076367-b759c7d7e738?auto=format&fit=crop&w=800&q=80", public_id: "v_vw_virtus", format: "jpg" }],
  },
  {
    name: "Maruti Suzuki Dzire VXI",
    brand: "Maruti Suzuki",
    type: "sedan",
    seats: 5,
    capacity: 5,
    pricePerKM: 12,
    pricePerHour: 150,
    isAvailable: true,
    isBooked: false,
    baseLocation: "Balasore",
    currentLocation: "Balasore Railway Station",
    licensePlate: "OD-01-IJ-5005",
    fuelType: "CNG / Petrol",
    transmission: "Manual",
    year: 2023,
    color: "Silky Silver",
    features: ["Super Fuel Economy", "Fastag", "Chilled AC", "Rear Armrest"],
    description: "Budget-friendly economical sedan ideal for everyday city travel and short trips.",
    images: [{ url: "https://images.unsplash.com/photo-1590362891991-f776e747a588?auto=format&fit=crop&w=800&q=80", public_id: "v_maruti_dzire", format: "jpg" }],
  },

  // --- 2. LUXURY & 7-SEATER SUVS ---
  {
    name: "Toyota Innova Crysta ZX 2.4",
    brand: "Toyota",
    type: "SUV",
    seats: 7,
    capacity: 7,
    pricePerKM: 20,
    pricePerHour: 280,
    isAvailable: true,
    isBooked: false,
    baseLocation: "Balasore",
    currentLocation: "Remuna Golei",
    licensePlate: "OD-01-KL-6006",
    fuelType: "Diesel",
    transmission: "Manual",
    year: 2023,
    color: "Super White",
    features: ["Captain Seats", "Ambient Roof Lighting", "Rear AC Vents", "7 Airbags"],
    description: "The gold standard for family vacations, business delegations, and group travel.",
    images: [{ url: "https://images.unsplash.com/photo-1533473359331-0135ef1b58bf?auto=format&fit=crop&w=800&q=80", public_id: "v_innova_crysta", format: "jpg" }],
  },
  {
    name: "Toyota Innova Hycross Hybrid",
    brand: "Toyota",
    type: "SUV",
    seats: 7,
    capacity: 7,
    pricePerKM: 24,
    pricePerHour: 320,
    isAvailable: true,
    isBooked: false,
    baseLocation: "Bhubaneswar",
    currentLocation: "BBI Airport Terminal 1",
    licensePlate: "OD-02-MN-7007",
    fuelType: "Strong Hybrid",
    transmission: "e-CVT Automatic",
    year: 2024,
    color: "Attitude Black Mica",
    features: ["Ottoman Reclining Seats", "Panoramic Sunroof", "EV Mode", "JBL 9-Speaker"],
    description: "Ultra-luxurious hybrid MPV offering first-class aircraft style reclining seats.",
    images: [{ url: "https://images.unsplash.com/photo-1563720223185-11003d516935?auto=format&fit=crop&w=800&q=80", public_id: "v_innova_hycross", format: "jpg" }],
  },
  {
    name: "Toyota Fortuner Legender 4x4",
    brand: "Toyota",
    type: "SUV",
    seats: 7,
    capacity: 7,
    pricePerKM: 32,
    pricePerHour: 450,
    isAvailable: true,
    isBooked: false,
    baseLocation: "Bhubaneswar",
    currentLocation: "Jayadev Vihar",
    licensePlate: "OD-02-OP-8008",
    fuelType: "Diesel",
    transmission: "Automatic",
    year: 2024,
    color: "Dual-tone Pearl White & Black",
    features: ["4x4 Drive", "Kick Sensor Tailgate", "JBL Audio", "Ventilated Seats"],
    description: "Dominant 4x4 flagship SUV built for VIP convoys and all-terrain road tours.",
    images: [{ url: "https://images.unsplash.com/photo-1519641471654-76ce0107ad1b?auto=format&fit=crop&w=800&q=80", public_id: "v_fortuner_legender", format: "jpg" }],
  },
  {
    name: "Mahindra XUV700 AX7 Luxury",
    brand: "Mahindra",
    type: "SUV",
    seats: 7,
    capacity: 7,
    pricePerKM: 22,
    pricePerHour: 300,
    isAvailable: true,
    isBooked: false,
    baseLocation: "Puri",
    currentLocation: "Grand Road Jagannath Temple",
    licensePlate: "OD-13-QR-9009",
    fuelType: "Diesel",
    transmission: "Automatic",
    year: 2024,
    color: "Midnight Blue",
    features: ["Skyroof", "ADAS Level 2", "Sony 3D Sound", "Wireless Android Auto"],
    description: "Feature-packed intelligent SUV with panoramic glass skyroof and cinema audio.",
    images: [{ url: "https://images.unsplash.com/photo-1609521263047-f8f205293f24?auto=format&fit=crop&w=800&q=80", public_id: "v_xuv700_ax7", format: "jpg" }],
  },
  {
    name: "Mahindra Scorpio-N Z8L",
    brand: "Mahindra",
    type: "SUV",
    seats: 7,
    capacity: 7,
    pricePerKM: 19,
    pricePerHour: 260,
    isAvailable: true,
    isBooked: false,
    baseLocation: "Cuttack",
    currentLocation: "CDA Sector 9",
    licensePlate: "OD-05-ST-1010",
    fuelType: "Diesel",
    transmission: "Automatic",
    year: 2023,
    color: "Dazzling Silver",
    features: ["4XPLOR Terrain Modes", "Sunroof", "Front & Rear Cameras", "Captain Chairs"],
    description: "Rugged yet refined ladder-frame SUV built for tough roads and hilly destinations.",
    images: [{ url: "https://images.unsplash.com/photo-1542282088-72c9c27ed0cd?auto=format&fit=crop&w=800&q=80", public_id: "v_scorpio_n", format: "jpg" }],
  },
  {
    name: "Tata Safari Dark Edition XZA+",
    brand: "Tata",
    type: "SUV",
    seats: 6,
    capacity: 6,
    pricePerKM: 21,
    pricePerHour: 290,
    isAvailable: true,
    isBooked: false,
    baseLocation: "Bhubaneswar",
    currentLocation: "Khandagiri Hub",
    licensePlate: "OD-02-UV-1111",
    fuelType: "Diesel",
    transmission: "Automatic",
    year: 2024,
    color: "Oberon Black",
    features: ["Signature Dark Aesthetic", "Ventilated 1st & 2nd Row", "JBL Sound", "ADAS"],
    description: "Premium blacked-out flagship SUV with captain seats and mood lighting.",
    images: [{ url: "https://images.unsplash.com/photo-1503376780353-7e6692767b70?auto=format&fit=crop&w=800&q=80", public_id: "v_tata_safari", format: "jpg" }],
  },
  {
    name: "Hyundai Creta SX(O) Knight",
    brand: "Hyundai",
    type: "SUV",
    seats: 5,
    capacity: 5,
    pricePerKM: 16,
    pricePerHour: 210,
    isAvailable: true,
    isBooked: false,
    baseLocation: "Balasore",
    currentLocation: "Chandipur Beach Road",
    licensePlate: "OD-01-WX-1212",
    fuelType: "Diesel",
    transmission: "Automatic",
    year: 2024,
    color: "Phantom Black",
    features: ["Panoramic Sunroof", "Trio Beam LED", "Electric Driver Seat", "Bose Audio"],
    description: "India's favorite compact luxury SUV with supreme ride height and comfort.",
    images: [{ url: "https://images.unsplash.com/photo-1583121274602-3e2820c69888?auto=format&fit=crop&w=800&q=80", public_id: "v_hyundai_creta", format: "jpg" }],
  },
  {
    name: "Kia Seltos GTX+ Facelift",
    brand: "Kia",
    type: "SUV",
    seats: 5,
    capacity: 5,
    pricePerKM: 16,
    pricePerHour: 210,
    isAvailable: true,
    isBooked: false,
    baseLocation: "Puri",
    currentLocation: "VIP Road Puri",
    licensePlate: "OD-13-YZ-1313",
    fuelType: "Petrol",
    transmission: "Dual Clutch (DCT)",
    year: 2024,
    color: "Imperial Blue",
    features: ["Dual 10.25-inch Screens", "360 Blind View Monitor", "Heads-Up Display"],
    description: "Stylish modern crossover with panoramic digital cockpit and dual-zone climate.",
    images: [{ url: "https://images.unsplash.com/photo-1549399542-7e3f8b79c341?auto=format&fit=crop&w=800&q=80", public_id: "v_kia_seltos", format: "jpg" }],
  },

  // --- 3. LUXURY & WEDDING FLEET ---
  {
    name: "Mercedes-Benz C-Class C200",
    brand: "Mercedes-Benz",
    type: "sedan",
    seats: 4,
    capacity: 4,
    pricePerKM: 45,
    pricePerHour: 650,
    isAvailable: true,
    isBooked: false,
    baseLocation: "Bhubaneswar",
    currentLocation: "Mayfair Lagoon Hotel Hub",
    licensePlate: "OD-02-LUX-001",
    fuelType: "Petrol",
    transmission: "9G-Tronic Automatic",
    year: 2024,
    color: "Obsidian Black",
    features: ["Chauffeur Driven", "Burmester 3D Surround", "64-Color Ambient Lights", "Panoramic Roof"],
    description: "Top-tier German luxury sedan suited for corporate executives, VIPs, and wedding entrances.",
    images: [{ url: "https://images.unsplash.com/photo-1618843479313-40f8afb4b4d8?auto=format&fit=crop&w=800&q=80", public_id: "v_benz_c200", format: "jpg" }],
  },
  {
    name: "BMW 3 Series Gran Limousine",
    brand: "BMW",
    type: "sedan",
    seats: 4,
    capacity: 4,
    pricePerKM: 48,
    pricePerHour: 700,
    isAvailable: true,
    isBooked: false,
    baseLocation: "Bhubaneswar",
    currentLocation: "BBI Airport Corporate Desk",
    licensePlate: "OD-02-LUX-002",
    fuelType: "Petrol",
    transmission: "Steptronic Sport",
    year: 2024,
    color: "Mineral White Metallic",
    features: ["Extended Wheelbase", "Vernasca Leather", "Harman Kardon Audio", "Curved Display"],
    description: "The long-wheelbase luxury saloon designed with royal rear seat legroom and comfort.",
    images: [{ url: "https://images.unsplash.com/photo-1555215695-3004980ad54e?auto=format&fit=crop&w=800&q=80", public_id: "v_bmw_3gl", format: "jpg" }],
  },
  {
    name: "Audi A4 Technology 40 TFSI",
    brand: "Audi",
    type: "sedan",
    seats: 4,
    capacity: 4,
    pricePerKM: 42,
    pricePerHour: 600,
    isAvailable: true,
    isBooked: false,
    baseLocation: "Cuttack",
    currentLocation: "Ring Road Viewpoint",
    licensePlate: "OD-05-LUX-003",
    fuelType: "Petrol",
    transmission: "S-Tronic 7-Speed",
    year: 2023,
    color: "Mythos Black Metallic",
    features: ["Virtual Cockpit Plus", "Bang & Olufsen 3D Sound", "Matrix LED Headlamps"],
    description: "Sophisticated executive luxury with quiet acoustic cabin and high-speed precision.",
    images: [{ url: "https://images.unsplash.com/photo-1603584173870-7f23fdae1b7a?auto=format&fit=crop&w=800&q=80", public_id: "v_audi_a4", format: "jpg" }],
  },
  {
    name: "Mercedes-Benz E-Class E220d LWB",
    brand: "Mercedes-Benz",
    type: "sedan",
    seats: 4,
    capacity: 4,
    pricePerKM: 60,
    pricePerHour: 900,
    isAvailable: true,
    isBooked: false,
    baseLocation: "Bhubaneswar",
    currentLocation: "Swosti Grand Hotel",
    licensePlate: "OD-02-LUX-004",
    fuelType: "Diesel",
    transmission: "Automatic",
    year: 2024,
    color: "Selenite Grey",
    features: ["Electric Reclining Rear Seats", "Air Suspension", "Chauffeur Package", "Soft-close Doors"],
    description: "The ultimate business class chauffeur limousine for luxury dignitaries and grand ceremonies.",
    images: [{ url: "https://images.unsplash.com/photo-1617814076367-b759c7d7e738?auto=format&fit=crop&w=800&q=80", public_id: "v_benz_eclass", format: "jpg" }],
  },

  // --- 4. ELECTRIC VEHICLES (EV) & HATCHBACKS ---
  {
    name: "Tata Nexon EV Long Range",
    brand: "Tata",
    type: "SUV",
    seats: 5,
    capacity: 5,
    pricePerKM: 13,
    pricePerHour: 170,
    isAvailable: true,
    isBooked: false,
    baseLocation: "Bhubaneswar",
    currentLocation: "Esplanade One Mall",
    licensePlate: "OD-02-EV-1414",
    fuelType: "Electric",
    transmission: "Automatic",
    year: 2024,
    color: "Fearless Purple",
    features: ["465km Range", "Zero Emissions", "V2V Charging", "JBL Cinematic Sound"],
    description: "Eco-friendly zero-emission electric SUV with whisper-quiet whisper drive.",
    images: [{ url: "https://images.unsplash.com/photo-1563720223185-11003d516935?auto=format&fit=crop&w=800&q=80", public_id: "v_nexon_ev", format: "jpg" }],
  },
  {
    name: "Hyundai i20 Asta (O)",
    brand: "Hyundai",
    type: "hatchback",
    seats: 5,
    capacity: 5,
    pricePerKM: 11,
    pricePerHour: 140,
    isAvailable: true,
    isBooked: false,
    baseLocation: "Balasore",
    currentLocation: "FM University Campus",
    licensePlate: "OD-01-EV-1515",
    fuelType: "Petrol",
    transmission: "Manual",
    year: 2023,
    color: "Fiery Red",
    features: ["Sunroof", "Wireless Charger", "Bose Audio", "Compact City Size"],
    description: "Nimble hatchback loaded with high-tech conveniences, ideal for quick city errands.",
    images: [{ url: "https://images.unsplash.com/photo-1541899481282-d53bffe3c35d?auto=format&fit=crop&w=800&q=80", public_id: "v_i20_asta", format: "jpg" }],
  },
  {
    name: "Maruti Suzuki Swift ZXI+",
    brand: "Maruti Suzuki",
    type: "hatchback",
    seats: 5,
    capacity: 5,
    pricePerKM: 10,
    pricePerHour: 130,
    isAvailable: true,
    isBooked: false,
    baseLocation: "Balasore",
    currentLocation: "OT Road Balasore",
    licensePlate: "OD-01-SW-1616",
    fuelType: "Petrol",
    transmission: "Manual",
    year: 2024,
    color: "Luster Blue",
    features: ["High Mileage", "Cruise Control", "LED Projector Lamps", "Fastag"],
    description: "Agile, peppy, and most pocket-friendly ride for city commuting and daily runs.",
    images: [{ url: "https://images.unsplash.com/photo-1590362891991-f776e747a588?auto=format&fit=crop&w=800&q=80", public_id: "v_swift_zxi", format: "jpg" }],
  },
];

const seed20Vehicles = async () => {
  try {
    console.log("Connecting to MongoDB Atlas at:", MONGO_URI.replace(/:([^@]+)@/, ":****@"));
    await mongoose.connect(MONGO_URI, { serverSelectionTimeoutMS: 10000 });
    console.log("✅ Connected to MongoDB successfully\n");

    console.log("Seeding 20 diverse vehicles across Sedans, SUVs, Luxury & EVs...");
    await Vehicle.deleteMany({});
    const inserted = await Vehicle.insertMany(twentyVehicles);

    console.log(`\n🎉 SUCCESS! Inserted ${inserted.length} vehicles into catalog:`);
    inserted.forEach((v, i) => {
      console.log(` ${i + 1}. [${v.type.toUpperCase()}] ${v.name} - ₹${v.pricePerKM}/km (${v.baseLocation})`);
    });

    console.log("\n=======================================================");
    console.log("✅ 20 VEHICLES SEEDED & READY FOR BOOKING IN FRONTEND!");
    console.log("=======================================================\n");

    await mongoose.disconnect();
    process.exit(0);
  } catch (error) {
    console.error("❌ Seeding failed:", error.message);
    process.exit(1);
  }
};

seed20Vehicles();
